---
name: Bun install

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/bun-script/package.json'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runtimes/bun-script
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
        with:
          bun-version: ${{ matrix.node-version }}
      - run: bun install
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: 'chore(bun): update lockfiles'
