---
name: Bun install

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/bun-script/package.json'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runtimes/bun-script
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@4573031972107e0af692492ee967d9022deafd7b # v1
        with:
          bun-version: ${{ matrix.node-version }}
      - run: bun install
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9
        with:
          message: 'chore(bun): update lockfiles'
