---
name: Deploy Cloudflare Workers

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/cloudflare-worker-expected/**'
      - 'runtimes/cloudflare-worker-actual/**'
      - 'runtimes/cloudflare-worker-native-expected/**'
      - 'runtimes/cloudflare-worker-native-actual/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          [
            cloudflare-worker-expected,
            cloudflare-worker-actual,
            cloudflare-worker-native-expected,
            cloudflare-worker-native-actual,
          ]
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - uses: cloudflare/wrangler-action@a08dc762e87e8754e0d56a16a35a70b406bc869f # v3.6.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          workingDirectory: runtimes/${{ matrix.test }}
