---
name: Deploy Cloudflare Workers

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/cloudflare-worker-expected/**'
      - 'runtimes/cloudflare-worker-actual/**'
      - 'runtimes/cloudflare-worker-native-expected/**'
      - 'runtimes/cloudflare-worker-native-actual/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          [
            cloudflare-worker-expected,
            cloudflare-worker-actual,
            cloudflare-worker-native-expected,
            cloudflare-worker-native-actual,
          ]
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Deploy
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - uses: cloudflare/wrangler-action@4c10c1822abba527d820b29e6333e7f5dac2cabd # tag=2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          workingDirectory: runtimes/${{ matrix.test }}
