---
name: Build Runtimes

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/node-cjs-script/**'
      - 'runtimes/node-esm-script/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  bun:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [0.1.x, '*']
    name: Bun ${{ matrix.bun-version }}
    # Bun can specify "--platform": browser | node | bun
    # Add bun condition to skunk client
    # https://github.com/oven-sh/bun#buntranspiler
    steps:
      - uses: actions/checkout@v3
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: git status

  deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x, canary]
    name: Deno ${{ matrix.deno-version }}
    # Run https://deno.land/manual/node/compatibility_mode#module-resolution mode on one test, and https://esm.sh/ on the other (https://deno.land/manual/node/cdns)
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: git status

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [node-cjs-script, node-esm-script]
        node-version: [10.x, 12.x, lts/*, current]
        exclude:
        - test: node-esm-script
          version: 10.x
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Node.js ${{ matrix.node-version }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Get Node.js major version
        uses: mathiasvr/command-output@v1
        id: version
        with:
          run: node -e "console.log(process.version.split('.')[0])"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.test }}-${{ steps.version.outputs.stdout }}
          path: runtimes/${{ matrix.test }}/artifacts/*.json
          if-no-files-found: error
          retention-days: 1
      - run: git status

  artifacts:
    runs-on: ubuntu-latest
    needs: [bun, deno, node]
    name: Commit artifacts to dashboard/public
    # if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
        with:
          path: dashboard/public/outputs
      - name: 'Dump download outputs'
        run: echo '${{ toJSON(steps.download.outputs) }}'
      - run: ls -R ${{steps.download.outputs.download-path}}
      - run: git status
      - run: npx prettier --ignore-path .gitignore --write dashboard/public/outputs
      - uses: EndBug/add-and-commit@v9
        with:
          commit: --no-verify
          message: 'chore(artifacts): update outputs'
          default_author: github_actions
