---
name: Build Runtimes

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/bun-script/**'
      - 'runtimes/deno-cdn-script/**'
      - 'runtimes/deno-compat-script/**'
      - 'runtimes/node-cjs-script/**'
      - 'runtimes/node-esm-script/**'
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # dump_contexts_to_log:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       id: github_context_step
  #       run: echo '${{ toJSON(github) }}'
  #     - name: Dump job context
  #       run: echo '${{ toJSON(job) }}'
  #     - name: Dump steps context
  #       run: echo '${{ toJSON(steps) }}'
  #     - name: Dump runner context
  #       run: echo '${{ toJSON(runner) }}'
  #     - name: Dump strategy context
  #       run: echo '${{ toJSON(strategy) }}'
  #     - name: Dump matrix context
  #       run: echo '${{ toJSON(matrix) }}'

  bun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Bun can specify "--platform": browser | node | bun
        # https://github.com/oven-sh/bun#buntranspiler
        # platform: [browser, node, bun]
        test: [bun-script]
        #bun-version: [0.1.x, '*']
        bun-version: [0.1.x]
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Bun ${{ matrix.bun-version }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: antongolub/action-setup-bun@bc198f5cb868ce282f0a72bdd7da3a06a5387f83 # tag=v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run test:expected
      - run: bun run test:actual
        timeout-minutes: 1
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{ matrix.test }}-${{ matrix.bun-version }}
          path: runtimes/${{ matrix.test }}/artifacts/*.json
          if-no-files-found: error
          retention-days: 1
      - run: git status

  deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [deno-cdn-script, deno-compat-script]
        deno-version: [1.x]
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Deno ${{ matrix.deno-version }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        if: matrix.test == 'deno-compat-script'
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
        if: matrix.test == 'deno-compat-script'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno task test
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{ matrix.test }}-${{ matrix.deno-version }}
          path: runtimes/${{ matrix.test }}/artifacts/*.json
          if-no-files-found: error
          retention-days: 1
      - run: git status

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [node-cjs-script, node-esm-script]
        node-version: [10.x, 12.x, 14.x, lts/*, current]
        exclude:
          - test: node-esm-script
            node-version: 10.x
          - test: node-esm-script
            node-version: 12.x
    defaults:
      run:
        working-directory: runtimes/${{ matrix.test }}
    name: Node.js ${{ matrix.node-version }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          cache: npm
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Get Node.js major version
        uses: mathiasvr/command-output@8dbf451add3db114df0114aa5e21a1efef8c5015 # tag=v1
        id: version
        with:
          run: node -e "console.log(process.version.split('.')[0])"
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{ matrix.test }}-${{ steps.version.outputs.stdout }}
          path: runtimes/${{ matrix.test }}/artifacts/*.json
          if-no-files-found: error
          retention-days: 1
      - run: git status

  artifacts:
    runs-on: ubuntu-latest
    # Re-enable when Bun starts working again
    # needs: [bun, deno, node]
    needs: [deno, node]
    name: Commit artifacts to dashboard/public
    # if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        id: download
        with:
          path: dashboard/public/outputs
      - name: 'Dump download outputs'
        run: echo '${{ toJSON(steps.download.outputs) }}'
      - run: ls -R ${{steps.download.outputs.download-path}}
      - run: git status
      - run: npx prettier --ignore-path .gitignore --write dashboard/public/outputs
      - run: git status
      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9 # tag=v9
        if: always()
        with:
          commit: --no-verify
          message: 'chore(artifacts): update outputs'
          default_author: github_actions
          pull: '--rebase --autostash'
